export const PAGE_LIMIT = 20;
export const FILTER_DEBOUNCE_MS = 400;
export const SELECTION_FLUSH_MS = 1_000;
export const SELECTION_INVALIDATE_DELAY_MS = 1_100;
export const ADD_QUEUE_FLUSH_INTERVAL_MS = 10_000;
export const ADD_INVALIDATE_DELAY_MS = ADD_QUEUE_FLUSH_INTERVAL_MS + 100;
